project_id = "reopolkbfkjpvofymnxu"

[functions.webhook-receiver]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-ai]
verify_jwt = false

[functions.whatsapp-agent]
verify_jwt = false